### ISSUE TITLE
multple $preslocs in to_xml function

### ISSUE THREAD

**Issue by sudoghut** [cga-harvard/tgaz#5]
The line 495 of tgza/tgw/webservice/api/placename.php is:

`function to_xml($pn, $spellings, $partofs, **$preslocs**, **$preslocs**, $subunits) {`

This causes an error below:

> "Redefinition of parameter $preslocs in...".

Finally, it works, when I changed it to:

`function to_xml($pn, $spellings, $partofs, $precbys, $preslocs, $subunits) {`

**Comment by vajlex** [comment]
thanks, updated it
