### ISSUE TITLE
Undefined variables in ...\www\tgaz\api\search_html.php on line 123

### ISSUE THREAD

**Issue by sudoghut** [cga-harvard/tgaz#6]
When I called the tgaz by using:

http://127.0.0.1/tgaz/placename?n=Tianbian

It can get a result, but with some errors:

![search_html_page](https://user-images.githubusercontent.com/8538710/56814855-9660d680-6872-11e9-8857-666a96c4d13e.png)

I changed .= to = in line 123:

`$pages = "<div class=\"pages\">" . $pg_nav . "</div><!-- end \"pages\" -->\n";`

and did the same thing to line 132:

    $t = "<div class=\"webmap_area\">"      
       . "<div id=\"map\" style=\"width: 600px; height: 260px\"></div>"
       . "</div>\n";

Then it works, but I don't know that whether it will cause other bugs.

**Comment by vajlex** [comment]
fixed in master
